config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cauthus

  root 'index#welcome'
  get '/about'=> 'index#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cauthu.rb
class Cauthu < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])

        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
   end
  end
end

app/controllers/cauthus_controller.rb
class CauthusController < ApplicationController
  before_action :set_cauthu, only: %i[ show edit update destroy ]

  # GET /cauthus or /cauthus.json
  def index
    @cauthus = Cauthu.all
  end

  # GET /cauthus/1 or /cauthus/1.json
  def show
  end

  # GET /cauthus/new
  def new
    @cauthu = Cauthu.new
  end

  # GET /cauthus/1/edit
  def edit
  end

  # POST /cauthus or /cauthus.json
  def create
    @cauthu = Cauthu.new(cauthu_params)

    respond_to do |format|
      if @cauthu.save
        format.html { redirect_to cauthu_url(@cauthu), notice: "Cauthu was successfully created." }
        format.json { render :show, status: :created, location: @cauthu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cauthu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cauthus/1 or /cauthus/1.json
  def update
    respond_to do |format|
      if @cauthu.update(cauthu_params)
        format.html { redirect_to cauthu_url(@cauthu), notice: "Cauthu was successfully updated." }
        format.json { render :show, status: :ok, location: @cauthu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cauthu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cauthus/1 or /cauthus/1.json
  def destroy
    @cauthu.destroy

    respond_to do |format|
      format.html { redirect_to cauthus_url, notice: "Cauthu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cauthu
      @cauthu = Cauthu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cauthu_params
      params.require(:cauthu).permit(:name, :club, :age)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def welcome
  	email='phanhuutuong2411@gmail.com';
  end

  def about
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cauthus_helper.rb
module CauthusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/cauthus/_cauthu.html.erb
<div id="<%= dom_id cauthu %>">
  <p>
    <strong>Name:</strong>
    <%= cauthu.name %>
  </p>

  <p>
    <strong>Club:</strong>
    <%= cauthu.club %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= cauthu.age %>
  </p>

</div>

app/views/cauthus/_form.html.erb
<%= form_with(model: cauthu) do |form| %>
  <% if cauthu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cauthu.errors.count, "error") %> prohibited this cauthu from being saved:</h2>

      <ul>
        <% cauthu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :club, style: "display: block" %>
    <%= form.text_field :club %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cauthus/edit.html.erb
<h1>Editing cauthu</h1>

<%= render "form", cauthu: @cauthu %>

<br>

<div>
  <%= link_to "Show this cauthu", @cauthu %> |
  <%= link_to "Back to cauthus", cauthus_path %>
  <%= button_to "Destroy this cauthu", @cauthu, method: :delete %>
</div>

app/views/cauthus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cauthus</h1>

<div id="cauthus">


<table  class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th class="col-3">Name</th>
      <th class="col-3">Club</th>
      <th class="col-3">Age</th>
      <th class="col-3">Action</th>
    </tr>
  </thead>
  <tbody>
  	<% @cauthus.each do |cauthu| %>
	    <tr>
	      <th scope="row"><%=cauthu.name%></th>
	      <td><%= cauthu.club %></td>
	      <td><%= cauthu.age%></td>
	      <td>
		      	<%= link_to "Show", cauthu, class:"btn btn-primary" %>
			    <%= link_to "Edit", edit_cauthu_path(cauthu), class:"btn btn-warning" %>
				<%= link_to "Destroy this cauthu", cauthu, data: { turbo_method: :delete,turbo_confirm: 'Are you sure?' },class:"btn btn-danger"%>
	      </td>
	    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New cauthu", new_cauthu_path, class:"btn btn-success" %>      
</div>

app/views/cauthus/new.html.erb
<h1>New cauthu</h1>

<%= render "form", cauthu: @cauthu %>

<br>

<div>
  <%= link_to "Back to cauthus", cauthus_path %>
</div>

app/views/cauthus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cauthu %>

<div style="display: inline-block;">
  <%= link_to "Back to cauthu", cauthus_path, class:"btn btn-primary"%>
  <%= link_to edit_cauthu_path(@cauthu), class:"btn btn-primary" do%> 
  	<i class="fa fa-user-plus"></i> edit
	<%end%>
  <%= link_to "Destroy this cauthu", @cauthu, data: { turbo_method: :delete,turbo_confirm: 'Are you sure?' },class:"btn btn-danger"%>
		
</div>

app/views/index/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#4fa3d2;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'HOME', root_path, class:'nav-link active'%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Phan Phan</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Cầu Thủ', cauthus_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class:'nav-link'%>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete,turbo_confirm: 'Are you sure want to sign out?' } , class:'nav-link'%>
        </li>
        <%else%>
         <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path , class:'nav-link'%>
          </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_registration_path , class:'nav-link'%>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/index/about.html.erb
<p>sin chào tui là tường 22 tuổi</p>

app/views/index/welcome.html.erb
<h1>Tường nè</h1>
<h2>Email: <%= @email %> </h2>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Huutuong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'index/header'%>
    <div class="container">
    <% if notice %>
      <p class="text-success"><%= notice %></p>
    <%end%>
       <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>